=== AlamoEngine-Tools/ModVerify/src/ModVerify/Resources/Schemas/2.2/baseline.json
{
  "$id": "https://AlamoEngine-Tools.github.io/schemas/mod-verify/2.2/baseline",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Represents a baseline for AET ModVerify",
  "type": "object",
  "$defs": {
    "location": {
      "type": "object",
      "properties": {
        "modPaths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "gamePath": {
          "type": "string"
        },
        "fallbackPaths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "modPaths",
        "gamePath",
        "fallbackPaths"
      ],
      "additionalProperties": false
    },
    "target": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "engine": {
          "enum": [ "Eaw", "Foc" ]
        },
        "location": {
          "$ref": "#/$defs/location"
        },
        "isGame": {
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "engine"
      ],
      "additionalProperties": false
    },
    "severity": {
      "enum": [ "Information", "Warning", "Error", "Critical" ]
    },
    "error": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "asset": {
          "type": "string"
        },
        "severity": {
          "$ref": "#/$defs/severity"
        },
        "context": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "id",
        "message",
        "asset",
        "severity",
        "context"
      ],
      "additionalProperties": false
    }
  },
  "properties": {
    "version": {
      "const": "2.2"
    },
    "minSeverity": {
      "$ref": "#/$defs/severity"
    },
    "errors": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/error"
      },
      "additionalItems": false
    },
    "target": {
      "$ref": "#/$defs/target"
    }
  },
  "required": [
    "version",
    "minSeverity",
    "errors"
  ],
  "additionalProperties": false
}

=== AlamoEngine-Tools/ModVerify/src/ModVerify.CliApp/Resources/Baselines/baseline-foc.json
{
  "version": "2.2",
  "target": {
    "name": "Forces of Corruption (SteamGold)",
    "engine": "Foc",
    "isGame": true,
    "version": "1.121.13.7360"
  },
  "minSeverity": "Information",
  "errors": [
    {
      "id": "CMDBAR03",
      "severity": "Information",
      "asset": "g_credit_bar",
      "message": "The CommandBar component \u0027g_credit_bar\u0027 is not supported by the game.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "b_beacon_t",
      "message": "The CommandBar component \u0027b_beacon_t\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "b_planet_left",
      "message": "The CommandBar component \u0027b_planet_left\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "b_planet_right",
      "message": "The CommandBar component \u0027b_planet_right\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "b_quick_ref",
      "message": "The CommandBar component \u0027b_quick_ref\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "balance_pip",
      "message": "The CommandBar component \u0027balance_pip\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "bm_title_4010",
      "message": "The CommandBar component \u0027bm_title_4010\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "bm_title_4011",
      "message": "The CommandBar component \u0027bm_title_4011\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "bribe_display",
      "message": "The CommandBar component \u0027bribe_display\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "bribed_icon",
      "message": "The CommandBar component \u0027bribed_icon\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "cs_ability_button",
      "message": "The CommandBar component \u0027cs_ability_button\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "cs_ability_text",
      "message": "The CommandBar component \u0027cs_ability_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_back",
      "message": "The CommandBar component \u0027encyclopedia_back\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_center_text",
      "message": "The CommandBar component \u0027encyclopedia_center_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_cost_text",
      "message": "The CommandBar component \u0027encyclopedia_cost_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_header_text",
      "message": "The CommandBar component \u0027encyclopedia_header_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_icon",
      "message": "The CommandBar component \u0027encyclopedia_icon\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_right_text",
      "message": "The CommandBar component \u0027encyclopedia_right_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "encyclopedia_text",
      "message": "The CommandBar component \u0027encyclopedia_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_bounty_hunter",
      "message": "The CommandBar component \u0027g_bounty_hunter\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_build",
      "message": "The CommandBar component \u0027g_build\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_conflict",
      "message": "The CommandBar component \u0027g_conflict\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_corruption_icon",
      "message": "The CommandBar component \u0027g_corruption_icon\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_corruption_text",
      "message": "The CommandBar component \u0027g_corruption_text\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_credit_bar",
      "message": "The CommandBar component \u0027g_credit_bar\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_enemy_hero",
      "message": "The CommandBar component \u0027g_enemy_hero\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_ground_icon",
      "message": "The CommandBar component \u0027g_ground_icon\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_ground_level",
      "message": "The CommandBar component \u0027g_ground_level\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_ground_level_pips",
      "message": "The CommandBar component \u0027g_ground_level_pips\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_ground_sell",
      "message": "The CommandBar component \u0027g_ground_sell\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_hero",
      "message": "The CommandBar component \u0027g_hero\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_hero_icon",
      "message": "The CommandBar component \u0027g_hero_icon\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_ability",
      "message": "The CommandBar component \u0027g_planet_ability\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_fleet",
      "message": "The CommandBar component \u0027g_planet_fleet\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_land_forces",
      "message": "The CommandBar component \u0027g_planet_land_forces\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_name",
      "message": "The CommandBar component \u0027g_planet_name\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_ring",
      "message": "The CommandBar component \u0027g_planet_ring\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_planet_value",
      "message": "The CommandBar component \u0027g_planet_value\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_political_control",
      "message": "The CommandBar component \u0027g_political_control\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_radar_blip",
      "message": "The CommandBar component \u0027g_radar_blip\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_radar_view",
      "message": "The CommandBar component \u0027g_radar_view\u0027 is not connected to a shell component.",
      "context": []
    },
    {
      "id": "CMDBAR04",
      "severity": "Information",
      "asset": "g_smuggled",
